### Numpy Arrays
Arrays support vectorised operations, while lists don’t.
Once an array is created, you cannot change its size. You will have to create a new array or overwrite the existing one.
Every array has one and only one dtype. All items in it should be of that dtype.
An equivalent numpy array occupies much less space than a python list of lists.


In [0]:
import numpy as np



In [6]:
list1=[1,2,3]
arr1= np.array(list1)
print("arr1:",arr1)
arr2 =arr1*2
print("arr2:",arr2)
print("arr2 type:",type(arr2))

arr1: [1 2 3]
arr2: [2 4 6]
arr2 type: <class 'numpy.ndarray'>


In [9]:
list2= [[1,2,3],[4,5,6],[7,8,9]]
arr3=np.array(list2)
print("arr3:",arr3)
print("arr3shape:",arr3.shape)
arr4=arr3+2
print("arr4:",arr4)

arr3: [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr3shape: (3, 3)
arr4: [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
arr5=np.array(list2,dtype=float)
print(arr5)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [14]:
arr5.astype('int')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr5.astype('str')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U32')

In [19]:
arr6 = np.array([1,2,4],dtype='object')
print(arr6)
print(arr6.tolist())

[1 2 4]
[1, 2, 4]


In [22]:
print("arr5.size:",arr5.size)
print("arr5.shape:",arr5.shape)
print("arr5.dtype:",arr5.dtype)

arr5.size: 9
arr5.shape: (3, 3)
arr5.dtype: float64


In [24]:
arr7=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
arr7.shape

(3, 4)

Extract first 2 rows

In [30]:
arr7[:2,:1]

array([[1],
       [4]])

In [31]:
arr7[:2,:2]

array([[1, 2],
       [4, 5]])

Extract first 3 rows and 2 columns

In [32]:
arr7[:3,:2]

array([[1, 2],
       [4, 5],
       [8, 9]])

In [35]:
arr7[:3,:4]

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
arr7

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
arr8=np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr8.shape)
print(arr8)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Boolean

In [43]:
arr9 = arr8 > 2
print(arr9)

[[False False]
 [ True  True]
 [ True  True]
 [ True  True]]


In [44]:
arr5

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [46]:
arr6=arr5[::-1,]
arr6

array([[7., 8., 9.],
       [4., 5., 6.],
       [1., 2., 3.]])

In [47]:
arr7 =arr5[::-1,::-1]
arr7

array([[9., 8., 7.],
       [6., 5., 4.],
       [3., 2., 1.]])

In [54]:
arr9=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11],[12.,13,14,15]])
arr9 = arr9[::-1,]
arr9

array([[12., 13., 14., 15.],
       [ 8.,  9., 10., 11.],
       [ 4.,  5.,  6.,  7.],
       [ 1.,  2.,  3.,  4.]])

### Not a number

In [59]:
arr10=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11],[12.,13,14,15]])
arr10.shape
arr10[1,3]=np.nan
arr10[3,3]=np.inf
arr10


array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6., nan],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., inf]])

In [60]:
missing_bool = np.isnan(arr10) | np.isinf(arr10)
arr10[missing_bool]=-1
arr10

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6., -1.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., -1.]])

In [74]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print(x1)
print(x1.ndim)
print("--------")
print(x2)
print(x2.ndim)
print("-------")
print(x3)
print(x3.ndim)

[5 0 3 3 7 9]
1
--------
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
2
-------
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
3


In [37]:
np.random.random(size=[2,2])

array([[0.03012328, 0.77600531],
       [0.55095838, 0.3810734 ]])

In [75]:
print(x1)

array([5, 0, 3, 3, 7, 9])

In [79]:
print(x1[-1])
print(x1[:-2])
print(x1[:2])

9
[5 0 3 3]
[5 0]


In [80]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [86]:
print(x2[0,0])
print(x2[1,1])
print(x2[2,0])
print(x2[-1,-3])

3
6
1
6


#### x[start:stop:step]
If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

In [87]:
arrm=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
arrm.shape

(3, 4)

In [91]:
print(arrm[:2,:2]) #access 2 rowsand 2 columns
print(arrm[:3,:2]) #access 3 rows and 2 columns
print(arrm[0,:1])


[[1 2]
 [4 5]]
[[1 2]
 [4 5]
 [8 9]]


In [0]:
arrm

Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [99]:
arrm1=arrm[:2,:2]
arrm1[0,0]=-1
arrm1
print(arrm)
print(arrm.shape)


[[-1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [105]:
print(arrm[:2,:2])

[[-1  2]
 [ 4  5]]


In [109]:
arrm[:2,::3]#2 rows and 3column

array([[-1,  4],
       [ 4,  7]])

In [108]:
x2=range(6)
x2

range(0, 6)

In [107]:
x = np.arange(10)
x
print(x)
print(x[-2])
print(x[:-2])
print(x[::2]) # alteranate 
print(x[::3])# every3rd one escape 2

[0 1 2 3 4 5 6 7 8 9]
8
[0 1 2 3 4 5 6 7]
[0 2 4 6 8]
[0 3 6 9]


###Array mean,max

In [64]:
print(arr10.mean())
print(arr10.max())

6.25
14.0


In [66]:
#np.arr10(mean,axis=0)
np.amean(arr10,axis=0)

AttributeError: ignored

### Random

In [5]:
import numpy as np
np.random.seed(100)
arr_random=np.random.randint(0,10,size=10,dtype=int)
arr_random

array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

In [26]:
# Random numbers between [0,1) of shape 2,2

np.random.rand(2,2)

array([[0.21010774, 0.4527399 ],
       [0.87014264, 0.06368104]])

In [29]:
# Normal distribution with mean=0 and variance=1 of shape 2,2
np.random.randn(2,2)

array([[ 0.26601635, -0.11379467],
       [ 1.01106614, -1.44077118]])

In [25]:
np.random.randint(0, 10, size=[2,2])

array([[4, 2],
       [5, 2]])

In [31]:
np.random.random()

0.6993589247765378

In [33]:
np.random.random(size=[2,2])

array([[0.64196495, 0.92002378],
       [0.29887635, 0.56874553]])

In [18]:
# Create the random state
rn = np.random.RandomState(100)
# Set the random seed


# Create random numbers between [0,1) of shape 2,2
#print(rn.random.rand(2,2))
print(rn.rand(2,2))

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]


In [21]:
np.random.seed(100)
print(np.random.rand(2,2))

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]


In [34]:
# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1]))  # picks more o's

['a' 'o' 'o' 'a' 'o' 'i' 'e' 'i' 'i' 'i']


### Unique,Count

In [52]:
np.random.seed(5)
arr_rand=np.random.randint(0,10,size=10)
print(arr_rand)
#np.random.randint(0,10,size=10) both aredifferent


[3 6 6 0 9 8 4 7 0 0]


In [54]:
# get Unique and their counts
unique,count=np.unique(arr_rand,return_counts=True)
print("unique:",unique)
print("counts:",count)

unique: [0 3 4 6 7 8 9]
counts: [3 1 1 2 1 1 1]


The difference between ravel and flatten is, the new array created using ravel is actually a reference to the parent array. So, any changes to the new array will affect the parent as well. But is memory efficient since it does not create a copy.

### Find max and min along a row and column

In [0]:
# Define func1d
def max_minus_min(x):
    return np.max(x) - np.min(x)

# Apply along the rows
print('Row wise: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# Apply along the columns
print('Column wise: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

### where

In [59]:
arr12=np.array([[1,2,3],[4,5,6]])
arr12.shape
b = np.where(arr12<4) 
print(b) 
print(arr12[b])

(array([0, 0, 0]), array([0, 1, 2]))
[1 2 3]


In [62]:
import numpy as np
arr_rand = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
print("Array: ", arr_rand)

# Positions where value > 5
index_gt5 = np.where(arr_rand > 5)
print("Positions where value > 5: ", index_gt5)
print(arr_rand[index_gt5])
# Take items at given index
arr_rand.take(index_gt5)

Array:  [8 8 3 7 7 0 4 2 5 2]
Positions where value > 5:  (array([0, 1, 3, 4]),)
[8 8 7 7]


array([[8, 8, 7, 7]])

In [63]:
# If value > 5, then yield 'gt5' else 'le5'
np.where(arr_rand > 5, 'gt5', 'le5')

array(['gt5', 'gt5', 'le5', 'gt5', 'gt5', 'le5', 'le5', 'le5', 'le5',
       'le5'], dtype='<U3')

argmax armin

In [76]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


https://stackoverflow.com/questions/28697993/numpy-what-is-the-logic-of-the-argmin-and-argmax-functions

In [74]:

print("rowwise maxvalue:",np.argmax(a,axis=1))# for every row what is max it gives values
print("rowise minvalue:",np.argmin(a,axis=1))#for very row what s min value




rowwise maxvalue: [2 2]
rowise minvalue: [0 0]


In [75]:
print("colwise maxvalue:",np.argmax(a,axis=0))
print("colwise minalue:",np.argmin(a,axis=0))

colwise maxvalue: [1 1 1]
colwise minalue: [0 0 0]


In [77]:
np.argmax(a) # if no axis mentioned,it will flatten it out  and index starts with 0

5

In [80]:
c=np.array([1,7,5,7,5])
print(np.argmax(c)) # it will first occurance of max value

1


In [81]:
d=np.array([[1,7,7],[7,8,9]])
print(np.argmax(d,axis=1))# it wil give first occurance in each row

[1 2]
